### ISSUE TITLE
It seems I introduced a bug 🥶

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-jupyter-notebooks#4]
@gansai Hi Ganesh, I updated from Vavr 0.9 to Vavr 0.10 and performed some minor refactorings.

Now the Jupyter notebook does not connect to the kernel anymore.
The docker image starts fine.

These are the changes that I performed since your last commit: f0bd6df...94118ab

I can't find the error. Do you have any idea?

Thanks for your help!

**Comment by danieldietrich** [comment]
The **Safari Browser** starts the docker image. The notebook shows the following in the browser console:

<img width="1447" alt="screenshot 2019-03-03 at 23 23 07" src="https://user-images.githubusercontent.com/743833/53702911-3fa7c500-3e0c-11e9-9dcc-a1a9c78418ec.png">

**Comment by danieldietrich** [comment]
The **Chrome Browser** also shows a kernel connection error in the console. I don't think that has something to do with our notebook / the json file...

<img width="556" alt="screenshot 2019-03-03 at 23 30 39" src="https://user-images.githubusercontent.com/743833/53702927-6c5bdc80-3e0c-11e9-950b-21ab46461ca4.png">

**Comment by danieldietrich** [comment]
We see an HTTP 502 error, which means:

> 502 Bad Gateway
> The server was acting as a gateway or proxy and received an invalid response from the upstream server.

Seems to be a server error.

**Comment by danieldietrich** [comment]
It seems to be a known issue (still open): jupyterhub/jupyter-server-proxy#39

**Comment by danieldietrich** [comment]
Maybe we need to build a docker image from the scratch --> [repo2docker](https://repo2docker.readthedocs.io/en/latest/usage.html)...

...and use the latest (Java) dependencies.

**Comment by gansai** [comment]
Hi @danieldietrich, the changes such you have committed doesn't seem to break the setup, as the Dockerfile is unmodified.

**Comment by danieldietrich** [comment]
Mmhh, ok. I will test it again.

**Comment by gansai** [comment]
Hi @danieldietrich, This issue is reproducible. I reproduced it within another repository.

How can changing vavr version to 0.10.0 cause a java kernel to break down in jupyter?

Probably we would need to check with https://github.com/SpencerPark/IJava as this is the kernel which is used to power the java jupyter notebook.

I shall recheck with the browser console error messages you have shared above.

**Comment by gansai** [comment]
Hi @danieldietrich, We have few alternatives apart from mybinder, to host jupyter notebooks. For example: Google colab. I found from this link : https://stackoverflow.com/questions/51287258/how-can-i-use-java-in-google-colab which will help us to try Java in Google colab. We can give it a try. ( I'm currently traveling, will give it a try and update you )

**Comment by danieldietrich** [comment]
Hi Ganesh,

that’s fine. I haven’t found the time yet but will look at mybinder.

Greets,

Daniel

**Comment by gansai** [comment]
Hi Daniel,
In Native form of Google Colab ( without extensions ), it does not support Java Kernel.

I have raised a query in stackoverflow related to this: https://stackoverflow.com/questions/55135887/is-it-possible-to-introduce-java-runtime-type-in-google-colab

Best Regards
Ganesh

**Comment by danieldietrich** [comment]
Thank you, I'm looking forward to their answer!

**Comment by SpencerPark** [comment]
Hi all, came here from the stackoverflow post. The issue with the Dockerfile is that I let a bit of variability in as I thought pinning down the `notebook` and `jupyterlab` package versions was enough. Turns out it wasn't and therefore images built after a certain date (not sure when exactly) pick up newer versions of libraries that are incompatible with the older notebook package.

Please take the new  [Dockerfile](https://github.com/SpencerPark/ijava-binder/blob/master/Dockerfile) and [requirements.txt](https://github.com/SpencerPark/ijava-binder/blob/master/requirements.txt) which should pin down all necessary dependencies so this issue never happens again. 

Not sure if there is any relation but see SpencerPark/ijava-binder#2

Thanks for making a binder with your Java notebooks!

**Comment by danieldietrich** [comment]
Hi @SpencerPark, thank you - that helps a lot 😊

**Comment by gansai** [comment]
@SpencerPark , now it works like a charm. Thank you.
@danieldietrich , please check now, it is working fine 👍

**Comment by danieldietrich** [comment]
Awesome, geeat work! 👍🏼
